# Site
name: "Memoirs"
title: "Athens for History Buffs"
description: "I will take you on the fabulous world of exploration. Travel, culture, lifestyle. Eat, Pray, Love!"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: "/travel-blog"
google_analytics: 'G-2KYPHM4M6E'
disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
email: ikrontiris@gmail.com

# Authors
authors:
  sal:
    name: Alexandros
    display_name: Alexandros
    avatar: 'assets/images/avatar-sal.png'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/donate/
    twitter: https://twitter.com/wowthemesnet
    description: "Alexandros Kostas is a historian with a deep passion for ancient Greece, having studied history at the University of Athens. After spending years in the academic world, he decided to take his love for history outside the classroom, leading specialized tours of archaeological sites across Athens. Alexandros is also known for his unique hobby of collecting and restoring ancient Greek pottery fragments, which he occasionally showcases in his blog."
  john:
    name: John
    display_name: John    
    avatar: 'assets/images/avatar.png'
    email: ikrontiris@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "Write a short description of the author here. You are currently previewing Memoirs demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
  - jekyll-seo-tag
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
