# Site
name: "Memoirs"
title: "Athens for History Buffs"
description: "Connecting the Dots: The Secrets of Athens' History for Modern City Travellers!"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: "/travel-blog"
url: "https://starbold.github.io"
google_analytics: 'G-2KYPHM4M6E'
disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
email: ikrontiris@gmail.com

# Authors
authors:
  sal:
    name: Dimitris
    display_name: Dimitris
    avatar: 'assets/images/dimitris.png'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/donate/
    twitter: https://twitter.com/wowthemesnet
    description: "Dimitris holds a PhD in Ancient History from the University of Thessaloniki. His research focuses on the daily lives of ancient Greeks, from their markets to their temples. Dimitrios loves exploring the lesser-known archaeological sites of Athens and revealing the stories they tell. He believes that every stone has a story waiting to be told."
  john:
    name: Eleni
    display_name: Georgiou    
    avatar: 'assets/images/avatar.png'
    email: ikrontiris@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "A seasoned historian and archaeologist, Eleni specializes in the study of ancient Greek art and architecture. She has contributed to numerous publications and documentaries on the subject. Eleni’s work is driven by a desire to connect the past with the present, making history accessible and engaging for all."
  john:
    name: Nikos
    display_name: Vassiliou    
    avatar: 'assets/images/avatar.png'
    email: ikrontiris@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "Nikos is an archaeologist with a focus on ancient Greek religion and mythology. He has led several tours around the historical sites of Athens, sharing his deep knowledge with travelers from around the globe. When not guiding tours, Nikos dedicates his time to researching and writing about the gods and goddesses that shaped ancient Greek culture."


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
  - jekyll-seo-tag
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
